#include<stdio.h>
#include<stdlib.h>
#include<assert.h>
#include<ASU_tools.h>
#include<tomography.h>

/*****************************************************************
 * This C function read formated data from files extracted
 * from .nc files.
 * 
 * Files contain numbers seperated by ",".
 * Four input files here, they are generated by "preprocess.sh"
 * script from downloaded data *.nc files:
 *
 *     v.dat      : velocity data.
 *     depth.data : depth layers.
 *     lat.data   : latitude data.
 *     lon.data   : longitude data.
 *
 * struct Tomography *data  ----  Pointer to where data is loaded.
 *
 * Note: 1. spaces are malloced here.
 *       2. lon is converted into -180 ~ 180 deg here.
 *
 * Shule Yu
 * May 26 2014
*****************************************************************/

void read_tomography(struct Tomography *data){

    int    verbose=0;

    FILE   *fp;
    int    count;
    double tmp;

    // Read velocity.
    fp=fopen("v.dat","r");
    assert(fp);

    data->Ndata=0;
    while(fscanf(fp,"%lf,",&tmp)==1){
        data->Ndata++;
    }
    fclose(fp);

    if (verbose==1){
        printf("Number of velocity points: %d\n",data->Ndata);
    }

    data->v=(double *)malloc(data->Ndata*sizeof(double));
    assert(data->v);

    fp=fopen("v.dat","r");
    for (count=0;count<data->Ndata;count++){
        fscanf(fp,"%lf,",data->v+count);
    }
    fclose(fp);




    // Read depth.
    fp=fopen("depth.dat","r");
    assert(fp);

    data->Ndepth=0;
    while(fscanf(fp,"%lf,",&tmp)==1){
        data->Ndepth++;
    }
    fclose(fp);

    if (verbose==1){
        printf("Number of depth points: %d\n",data->Ndepth);
    }

    data->depth=(double *)malloc(data->Ndepth*sizeof(double));
    assert(data->depth);

    fp=fopen("depth.dat","r");
    for (count=0;count<data->Ndepth;count++){
        fscanf(fp,"%lf,",data->depth+count);
    }
    fclose(fp);




    // Read Lat.
    fp=fopen("lat.dat","r");
    assert(fp);

    data->Nlat=0;
    while(fscanf(fp,"%lf,",&tmp)==1){
        data->Nlat++;
    }
    fclose(fp);

    if (verbose==1){
        printf("Number of latitude points: %d\n",data->Nlat);
    }

    data->lat=(double *)malloc(data->Nlat*sizeof(double));
    assert(data->lat);

    fp=fopen("lat.dat","r");
    for (count=0;count<data->Nlat;count++){
        fscanf(fp,"%lf,",data->lat+count);
    }
    fclose(fp);




    // Read Lon.
    fp=fopen("lon.dat","r");
    assert(fp);

    data->Nlon=0;
    while(fscanf(fp,"%lf,",&tmp)==1){
        data->Nlon++;
    }
    fclose(fp);

    if (verbose==1){
        printf("Number of longitude points: %d\n",data->Nlon);
    }

    data->lon=(double *)malloc(data->Nlon*sizeof(double));
    assert(data->lon);

    fp=fopen("lon.dat","r");
    for (count=0;count<data->Nlon;count++){
        fscanf(fp,"%lf,",data->lon+count);
		lon2180(data->lon[count]);
    }
    fclose(fp);


	// Find minmax of each dimension.
	int tmpint;

    data->MinLon=min_vald(data->lon,data->Nlon,&tmpint);
    data->MaxLon=max_vald(data->lon,data->Nlon,&tmpint);
    data->MinLat=min_vald(data->lat,data->Nlat,&tmpint);
    data->MaxLat=max_vald(data->lat,data->Nlat,&tmpint);
    data->MinD=min_vald(data->depth,data->Ndepth,&tmpint);
    data->MaxD=max_vald(data->depth,data->Ndepth,&tmpint);

    return;
}
